[release-3.11] Bug 1854434: UPSTREAM: 94112: Improve diff check in endpoints controller syncService
openshift/origin pull request #25424
Opened 2020-08-19 21:52 UTC by damemi

The EndpointsController compares labels and subsets to determine if an update is needed. It sorts the calculated subsets on a service but does not sort the subsets it compares to. 

In addition, we compare the *Endpoint's* labels to the *Service's* labels, and while the Endpoint may have a `headless` label, the service does not and also leads to false no-op update calls.

This leads to *severe* performance issues in large clusters, with unimportant updates being called on as many as 2/3 (or more) of the services in the cluster at every informer resync. On clusters with thousands of services, this causes significant degradation.

From what we can tell, this issue exists at least as far back as 1.11 (likely earlier) and should be backported.

Before change:
```
$ oc get services --all-namespaces | wc -l
      70
$ oc logs pod/kube-controller-manager-ci-ln-j9ksx82-f76d1-x65w5-master-1 -n openshift-kube-controller-manager -c kube-controller-manager | grep endpoints_controller | grep -c "About to update endpoints"
64

$ oc logs pod/kube-controller-manager-ci-ln-j9ksx82-f76d1-x65w5-master-1 -n openshift-kube-controller-manager -c kube-controller-manager | grep endpoints_controller | grep -c "Update endpoints for"
22
```

These numbers correlate to how many total services are being checked vs how many are being updated. As you can see, about 1/3 of the services in the cluster are being updated without any changes happening.

After change:

```
$ oc logs pod/kube-controller-manager-ci-ln-5kyrnwk-f76d1-5qbkz-master-2 -n openshift-kube-controller-manager -c kube-controller-manager | grep endpoints_controller | grep -c "About to update"

64
$ oc logs pod/kube-controller-manager-ci-ln-ihf6wv2-f76d1-ch2s6-master-1 -n openshift-kube-controller-manager -c kube-controller-manager | grep endpoints_controller | grep -c "Update endpoints for"
1
```

See upstream: https://github.com/kubernetes/kubernetes/pull/94112
/priority critical-urgent
/kind bug

2020-08-19 21:52 UTC, damemi commented
/cc @soltysh @mfojtik

2020-08-19 22:04 UTC, damemi commented
@tsmetana

2020-08-19 22:44 UTC, damemi commented
/retest

2020-08-20 08:59 UTC, tsmetana commented
/retest

2020-08-20 10:08 UTC, soltysh requested changes
/assign

2020-08-20 10:08 UTC, soltysh commented on vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
> +		apiequality.Semantic.DeepEqual(utillabels.CloneAndRemoveLabel(currentEndpoints.Labels, v1.IsHeadlessService), service.Labels) {
Missing `utillabels` import and `IsHeadlessService` is not present in 1.11, so this entire line is not needed for 3.11.

2020-08-20 10:08 UTC, soltysh commented on vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
> +		apiequality.Semantic.DeepEqual(endpoints.RepackSubsets(currentEndpoints.Subsets), subsets) &&
Why `RepackSubsets`, what was the problem with sorting function?

2020-08-20 13:38 UTC, cuppett commented
/bugzilla refresh

2020-08-20 13:44 UTC, closed without merging