Remove 'oc explain' tests for the CRs in metal3.io
openshift/origin pull request #25722
Opened 2020-11-30 22:55 UTC by sadasu

2020-11-30 22:57 UTC, sadasu commented
/cc @stts @soltysh

2020-12-01 00:23 UTC, stbenjam commented
Given we're close to feature freeze and this is now blocking work, I'm inclined to just say let's merge this one and figure out when and if to add this test when the platform is baremetal.

/lgtm

2020-12-01 00:24 UTC, stbenjam commented
/assign @sttts

2020-12-01 09:52 UTC, soltysh requested changes
> Given we're close to feature freeze and this is now blocking work, I'm inclined to just say let's merge this one and figure out when and if to add this test when the platform is baremetal.

This is not an argument for removing tests. Where this is failing? I spoke with both @sadasu and @sttts about it, I'm willing to make this conditional but from what I've checked on an AWS installation both of these resources are there and have proper `oc explain` data.

2020-12-01 09:52 UTC, soltysh commented
/hold

2020-12-01 11:40 UTC, stbenjam commented
It was failing on https://github.com/openshift/cluster-baremetal-operator/pull/81, but it looks like @sadasu fixed it. This might not be needed.

2020-12-01 15:13 UTC, sadasu commented
> It was failing on [openshift/cluster-baremetal-operator#81](https://github.com/openshift/cluster-baremetal-operator/pull/81), but it looks like @sadasu fixed it. This might not be needed.

I didn't do anything specific in my PR to fix it. It just didn't happen in the next run. So, I suspect a timing issue.

2020-12-01 15:13 UTC, closed without merging