Add statefulsets to single-replica topology test
openshift/origin pull request #25885
Opened 2021-02-11 09:53 UTC by omertuc

This test only tested deployments until now, now it will also test StatefulSets

2021-02-11 09:56 UTC, romfreiman commented
@simonpasquier

2021-02-11 11:08 UTC, simonpasquier commented on test/extended/single_node/topology.go
> +	}
(nit) shorter version
```suggestion
	namespaceInfraStatefulSets, _ := infrastructureNamespaces[statefulSet.Namespace]
```

2021-02-11 11:08 UTC, simonpasquier commented on test/extended/single_node/topology.go
> +		// No known OpenShift StatefulSets are considered "infrastructure" for now
I would expect prometheus-k8s and alertmanager-main to be listed here.

2021-03-01 12:25 UTC, omertuc commented
/test e2e-aws-serial

2021-03-01 12:25 UTC, omertuc commented
/test pj-rehearse

2021-03-01 12:27 UTC, omertuc commented
/retest

2021-03-01 13:54 UTC, omertuc commented
/test e2e-gcp-disruptive

2021-03-25 11:54 UTC, simonpasquier commented
you should be able to remove the exception for the monitoring components: CMO supports the single-node topology thanks to https://github.com/openshift/cluster-monitoring-operator/pull/1077.

2021-03-25 12:22 UTC, omertuc commented
> you should be able to remove the exception for the monitoring components: CMO supports the single-node topology thanks to [openshift/cluster-monitoring-operator#1077](https://github.com/openshift/cluster-monitoring-operator/pull/1077).

Great, done

2021-03-26 15:53 UTC, omertuc commented
/test e2e-gcp-csi
/test e2e-agnostic-cmd
/test e2e-gcp-upgrade

2021-03-26 18:23 UTC, omertuc commented
/test e2e-gcp-upgrade

2021-03-29 07:59 UTC, omertuc commented
/test e2e-agnostic-cmd
/test e2e-gcp-upgrade

2021-03-30 07:19 UTC, simonpasquier reviewed
/approve
one small nit

2021-03-30 07:19 UTC, simonpasquier commented on test/extended/single_node/topology.go
> +			"%s in %s namespace has wrong number of replicas", name, namespace)
```suggestion
		Expect(replicas).To(Equal(1),
			"%s in %s namespace expected to have 1 replica but got %d", name, namespace, replicas)
```

2021-03-30 20:02 UTC, omertuc commented
/assign @mfojtik

2021-03-30 20:03 UTC, romfreiman commented
/lgtm

2021-03-31 13:57 UTC, omertuc commented
/test e2e-gcp-upgrade
/test e2e-aws-disruptive
/test e2e-aws-serial
/test e2e-aws-fips
/test e2e-gcp-csi
/test e2e-agnostic-cmd

2021-03-31 15:57 UTC, omertuc commented
/test e2e-aws-fips

2021-03-31 21:51 UTC, omertuc commented
/test e2e-aws-disruptive
/test e2e-gcp-upgrade
/test e2e-agnostic-cmd
/test e2e-aws-fips

2021-04-01 07:12 UTC, omertuc commented
/test e2e-aws-disruptive

2021-04-01 20:22 UTC, omertuc commented
/test e2e-aws-disruptive

2021-04-20 11:51 UTC, omertuc commented
/test ?

2021-04-20 11:51 UTC, omertuc commented
/test e2e-aws-single-node

2021-04-20 11:51 UTC, omertuc commented
/retest

2021-04-20 14:15 UTC, omertuc commented
/retest

2021-04-20 18:06 UTC, omertuc commented
/retest

2021-04-20 22:26 UTC, omertuc commented
/retest

2021-04-21 08:21 UTC, omertuc commented
/retest

2021-04-28 12:43 UTC, omertuc commented
/retest

2021-04-28 17:09 UTC, omertuc commented
/retest

2021-04-29 11:00 UTC, eranco74 commented
/lgtm

2021-05-03 08:24 UTC, omertuc commented
/assign @soltysh

2021-05-04 12:05 UTC, soltysh requested changes

2021-05-04 12:05 UTC, soltysh commented on test/extended/single_node/topology.go
> +			t.Logf("%s in namespace %s has one replica, consider taking it off the topology allow-list",
I'd suggest using `framework.Logf` instead of this construct to be consistent with other tests.

2021-05-04 12:05 UTC, soltysh commented on test/extended/single_node/topology.go
> +			t := GinkgoT()
It looks like you're importing ginkgo w/o alias, which for consistency and readability should be `g`

2021-05-04 12:23 UTC, omertuc commented
First force push - rebase

2021-05-04 12:23 UTC, omertuc commented
Second force push - review comments fixed

2021-05-04 13:39 UTC, omertuc commented
/retest

2021-05-04 13:39 UTC, omertuc commented
/test e2e-aws-single-node

2021-05-04 16:58 UTC, omertuc commented
/retest

2021-05-04 19:30 UTC, omertuc commented
/retest

2021-05-04 21:42 UTC, omertuc commented
/retest

2021-05-05 07:55 UTC, omertuc commented
/retest

2021-05-05 10:23 UTC, omertuc commented
/retest

2021-05-05 12:26 UTC, omertuc commented
/retest

2021-05-05 22:05 UTC, omertuc commented
/retest

2021-05-06 08:47 UTC, omertuc commented
/retest

2021-05-06 13:44 UTC, omertuc commented
/retest

2021-05-06 15:26 UTC, omertuc commented
/retest

2021-05-10 19:45 UTC, soltysh approved these changes
/lgtm
/approve

2021-05-19 17:37 UTC, omertuc commented
> New changes are detected. LGTM label has been removed.

Force push for rebase...

2021-05-19 17:39 UTC, romfreiman commented
/lgtm

2021-06-14 12:19 UTC, omertuc commented
/retest

2021-06-14 12:19 UTC, omertuc commented
/test e2e-aws-single-node

2021-06-15 07:09 UTC, omertuc commented
/retest

2021-06-15 12:16 UTC, omertuc commented
/retest

2021-06-15 17:32 UTC, omertuc commented
/retest

2021-06-15 21:12 UTC, omertuc commented
/retest

2021-06-16 00:56 UTC, merged