test: remove apk add tcpdump to internal ports test
openshift/origin pull request #26008
Opened 2021-03-23 10:54 UTC by stbenjam

The connectivity test for ports 9000-9999 tries to install tcpdump via
apk, and this appears to only be used for debugging purposes. In order
to run these tests disconnected, we can't have dependencies running
in the container that try to reach out to the internet. Currently this
test fails on IPv6 disconnected installs.

2021-03-23 10:55 UTC, stbenjam commented
/assign @smarterclayton

2021-03-23 11:27 UTC, stbenjam commented
/assign @danwinship @dcbw 

I think either of you could approve this too, thanks!

2021-03-23 12:29 UTC, danwinship requested changes

2021-03-23 12:29 UTC, danwinship commented on test/extended/networking/internal_ports.go
> +								Command: []string{"/agnhost", "netexec", fmt.Sprintf("--http-port=%v --udp-port=%v", nodeTCPPort, nodeUDPPort)},
```suggestion
								Command: []string{"/agnhost", "netexec", fmt.Sprintf("--http-port=%v", nodeTCPPort), fmt.Sprintf("--udp-port=%v", nodeUDPPort)},
```

2021-03-23 14:02 UTC, stbenjam commented on test/extended/networking/internal_ports.go
> +								Command: []string{"/agnhost", "netexec", fmt.Sprintf("--http-port=%v --udp-port=%v", nodeTCPPort, nodeUDPPort)},
Thanks

2021-03-23 17:48 UTC, stbenjam commented
@danwinship Can you take a look again? Thanks!

2021-03-25 12:03 UTC, stbenjam commented
@danwinship @smarterclayton Could you take a look at this please? Thanks.

2021-03-25 12:09 UTC, danwinship commented
/lgtm

2021-03-25 18:34 UTC, stbenjam commented
/retest

2021-03-25 22:51 UTC, stbenjam commented
/retest

2021-03-26 01:29 UTC, stbenjam commented
/test e2e-metal-ipi-ovn-ipv6

2021-03-30 12:43 UTC, stbenjam commented
/test e2e-metal-ipi-ovn-ipv6

2021-03-30 14:58 UTC, stbenjam commented
/test e2e-metal-ipi-ovn-ipv6

2021-03-30 21:22 UTC, stbenjam commented
/retest

2021-03-31 02:05 UTC, merged