Bug 1988264: initializeTestFramework: initialize TextContext ip family
openshift/origin pull request #26361
Opened 2021-07-30 08:18 UTC by fedepaol

Some tests rely on the TestContext IPFamily field, that is being initialized in the upstream ginkgo suites but not in origin's one.
Here we add the initialization in initializeTestFramework based on config.HasIPV6 / config.HasIPV4.

This is the manual cherry-pick of https://github.com/openshift/origin/pull/26140

2021-07-30 08:20 UTC, fedepaol commented
/cc @danwinship

2021-07-30 08:39 UTC, fedepaol commented
/hold

2021-07-30 20:22 UTC, danwinship commented
/lgtm

2021-08-04 11:42 UTC, fedepaol commented
/hold cancel

2021-08-04 11:43 UTC, fedepaol commented
/retest

2021-08-19 13:04 UTC, danwinship requested changes

2021-08-19 13:04 UTC, danwinship commented on test/extended/util/annotate/rules.go
> +			`\[sig-network\] Networking should provide Internet connection for containers \[Feature:Networking-IPv6\]`,
this needs to remain in `[Disabled:Broken]` as in #26362

2021-08-23 12:23 UTC, danwinship commented
/lgtm cancel
(as above, one of the skips needs to be changed to basically merge in a later fix from master)

2021-08-30 16:49 UTC, fedepaol commented
> /lgtm cancel
> (as above, one of the skips needs to be changed to basically merge in a later fix from master)

Done

2021-08-30 16:50 UTC, fedepaol commented
@danwinship ptal

2021-09-01 15:57 UTC, danwinship commented
/lgtm

2021-09-10 13:56 UTC, ardaguclu commented
/test e2e-metal-ipi-ovn-dualstack

2022-02-07 22:51 UTC, closed without merging