Bug 2003239: builds: skip private git repo tests outside of CI
openshift/origin pull request #26461
Opened 2021-09-10 18:10 UTC by yselkowitz

These tests depend on a secret which is only available on the CI step
registry, and therefore fail when run externally.

/cc @adambkaplan

2021-09-10 20:26 UTC, yselkowitz commented
Tests in question passed (not skipped), failures are flakes.
/retest
/assign @adambkaplan

2021-09-10 20:44 UTC, adambkaplan requested changes

2021-09-10 20:44 UTC, adambkaplan commented on test/extended/builds/gitauth.go
> +				}
Check that the error is a 404/not found.

```suggestion
				if errors.IsNotFound(err) {
					g.Skip("required secret build-e2e-github-secrets/github-http-token is missing")
				}
```

2021-09-10 20:44 UTC, adambkaplan commented on test/extended/builds/gitauth.go
> +				}
Check for 404/not found:

```suggestion
				if errors.IsNotFound(err) {
					g.Skip("required secret build-e2e-github-secrets/github-ssh-privatekey is missing")
				}
```

2021-09-12 07:08 UTC, yselkowitz commented
Failures are unrelated.
/retest

2021-09-13 15:43 UTC, yselkowitz commented
@adambkaplan incorporated your suggestions.  Successfully retested with a nightly and has passed CI again.

2021-09-20 14:37 UTC, yselkowitz commented
> @adambkaplan incorporated your suggestions. Successfully retested with a nightly and has passed CI again.

Ping @adambkaplan ?

2021-09-20 18:17 UTC, adambkaplan reviewed
Need to check that some other error didn't occur.

2021-09-20 18:17 UTC, adambkaplan commented on test/extended/builds/gitauth.go
> +				}
```suggestion
				if err != nil && kerrors.IsNotFound(err) {
					g.Skip("required secret build-e2e-github-secrets/github-http-token is missing")
				} else {
					o.Expect(err).NotTo(o.HaveOccurred())
				}
```

2021-09-20 18:17 UTC, adambkaplan commented on test/extended/builds/gitauth.go
> +				}
```suggestion
				if err != nil && kerrors.IsNotFound(err) {
					g.Skip("required secret build-e2e-github-secrets/github-ssh-privatekey is missing")
				} else {
					o.Expect(err).NotTo(o.HaveOccurred())
				}
```

2021-09-20 18:17 UTC, adambkaplan commented
/approve

Marking this PR as OK to merge pending my suggested changes.

2021-09-24 16:19 UTC, yselkowitz commented
/retest

2021-09-24 16:47 UTC, yselkowitz commented
Failures all seem unrelated.
/retest

2021-09-24 18:19 UTC, yselkowitz commented
/retest

2021-09-24 19:51 UTC, yselkowitz commented
/retest

2021-09-24 22:12 UTC, yselkowitz commented
@adambkaplan ready for re-review, remaining failures are unrelated
/retest

2021-09-26 01:24 UTC, yselkowitz commented
/retest

2021-09-30 16:27 UTC, yselkowitz commented
/retest

2021-09-30 18:26 UTC, yselkowitz commented
Remaining failure is unrelated.
/retest

2021-10-04 19:54 UTC, gabemontero commented
/skip

/lgtm

2021-10-04 23:54 UTC, merged