Attempt multiple different token requests
openshift/origin pull request #26916
Opened 2022-03-17 09:06 UTC by arjunrn

The token request with client header authorization does not encode the header client identifier payload with URLEscape like the other request methods. The current oauth-server implements it so but this behavior has changed in newer versions of the dependency. So now the test which makes the token requests can multiple requests to fetch the token and as long as one of them succeeds the test is considered as succeeded.

2022-03-17 12:23 UTC, arjunrn commented
/retest

2022-03-21 10:54 UTC, slaskawi requested changes
Only one nitpick. Otherwise looks good.

2022-03-21 10:54 UTC, slaskawi commented on test/extended/oauth/client_secret.go
> +	e2eskipper "k8s.io/kubernetes/test/e2e/framework/skipper"
Please leave the imports where they were. This change is not required.

2022-03-22 06:48 UTC, slaskawi approved these changes
/lgtm
/approve

2022-03-22 08:53 UTC, arjunrn commented
/retest

2022-03-22 12:53 UTC, stlaz commented on test/extended/oauth/client_secret.go
> +	reqNoURLEscape.Header.Set("Authorization", fmt.Sprintf("Basic %s", base64.StdEncoding.EncodeToString([]byte("oauth-client-with-plus:secret+with+plus"))))
Please use https://pkg.go.dev/net/http#Request.SetBasicAuth for setting basic auth

2022-03-22 12:53 UTC, stlaz commented on test/extended/oauth/client_secret.go
> +	reqURLEscape.Header.Set("Authorization", fmt.Sprintf("Basic %s", base64.StdEncoding.EncodeToString([]byte("oauth-client-with-plus:secret%2Bwith%2Bplus"))))
use the library basic auth setter here too, please

2022-03-22 13:15 UTC, stlaz commented
/lgtm

2022-03-22 15:10 UTC, merged