egressip: avoid curl hanging when sending probes
openshift/origin pull request #27379
Opened 2022-08-26 15:34 UTC by jcaamano

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

2022-08-26 15:34 UTC, jcaamano commented
@andreaskaris

PTAL

2022-09-01 09:26 UTC, jcaamano commented
/retest

2022-09-08 13:59 UTC, andreaskaris commented
/retest

2022-09-08 14:42 UTC, andreaskaris requested changes

2022-09-08 14:42 UTC, andreaskaris commented on test/extended/networking/egressip_helpers.go
> +			output, err := runOcWithRetry(oc.AsAdmin(), "exec", proberPod.Name, "--", "curl", "--max-time 15", "-s", request)
TL;DR: `"--max-time", "15"`

I ran:
~~~
./openshift-tests run openshift/conformance/serial --run "\[sig-network\]\[Feature:EgressIP\]"
~~~

And got:
~~~
StdErr>
curl: option --max-time 15: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
~~~

Should be:
~~~
diff --git a/test/extended/networking/egressip_helpers.go b/test/extended/networking/egressip_helpers.go
index 0aa7deccd1..019bdec402 100644
--- a/test/extended/networking/egressip_helpers.go
+++ b/test/extended/networking/egressip_helpers.go
@@ -1233,7 +1233,7 @@ func sendProbesToHostPort(oc *exutil.CLI, proberPod *v1.Pod, url, targetProtocol
                go func() {
                        defer wg.Done()
                        time.Sleep(time.Duration(n) * time.Millisecond)
-                       output, err := runOcWithRetry(oc.AsAdmin(), "exec", proberPod.Name, "--", "curl", "--max-time 15", "-s", request)
+                       output, err := runOcWithRetry(oc.AsAdmin(), "exec", proberPod.Name, "--", "curl", "--max-time", "15", "-s", request)
                        // Report errors.
                        if err != nil {
                                errChan <- fmt.Errorf("Query failed. Request: %s, Output: %s, Error: %v", request, output, err)
~~~

2022-09-08 15:15 UTC, andreaskaris commented
/lgtm

2022-09-08 18:47 UTC, andreaskaris commented
/retest

2022-09-09 08:42 UTC, andreaskaris commented
/retest-failed

2022-09-09 08:42 UTC, andreaskaris commented
/retest

2022-09-09 12:50 UTC, andreaskaris commented
/retest

2022-09-09 16:48 UTC, andreaskaris commented
/test e2e-aws-ovn-serial
Incredible - this constantly fails on 2-3 completely unrelated tests

2022-09-09 20:44 UTC, andreaskaris commented
/retest

2022-09-10 11:02 UTC, andreaskaris commented
/retest

2022-09-16 16:45 UTC, andreaskaris commented
/retest

2022-09-16 18:28 UTC, andreaskaris commented
/retest

2022-09-28 17:49 UTC, dcbw commented
/approve

2022-09-29 10:15 UTC, jcaamano commented
/retest-required

2022-09-29 19:09 UTC, jcaamano commented
/hold cancel
/retest-required

2022-09-30 02:00 UTC, merged