OCPBUGS-6902: Fix dns-test
openshift/origin pull request #27699
Opened 2023-02-01 11:28 UTC by derekhiggins

/hold

2023-02-01 11:38 UTC, derekhiggins commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm-upgrade

2023-02-01 11:57 UTC, derekhiggins commented
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm-upgrade

2023-02-01 14:20 UTC, derekhiggins commented
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm-upgrade

2023-02-01 17:46 UTC, derekhiggins commented
/unhold
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm-upgrade

2023-02-02 08:55 UTC, derekhiggins commented
/jira refresh
@deads2k mind taking a look

2023-02-02 08:56 UTC, derekhiggins commented
/cc @droslean

2023-02-02 10:22 UTC, droslean commented
/lgtm
/approve
/hold

Holding the PR to let @deads2k review it as well.

2023-02-02 10:50 UTC, derekhiggins commented
Here is the ipv6 upgrade payload job passing with this PR (its failure rate is somewhere around 90% at the moment)
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-27699-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6/1620841151944724480

2023-02-03 11:10 UTC, derekhiggins commented
/test required

2023-02-03 11:11 UTC, derekhiggins commented
/retest-required

2023-02-07 09:54 UTC, derekhiggins commented
/retest-required

2023-02-08 09:53 UTC, derekhiggins commented
> Holding the PR to let @deads2k review it as well.
Hi @deads2k would you have a few minutes to take a look

2023-02-09 15:28 UTC, soltysh requested changes
/hold
since the alternative is much better

2023-02-09 15:28 UTC, soltysh commented on test/e2e/upgrade/dns/dns.go
> +	time.Sleep(1 * time.Minute)
Sleeps are always a bad option, a better alternative is here: https://github.com/openshift/origin/pull/27715

2023-02-09 15:33 UTC, closed without merging