OCPBUGS-32293: Skips Jenkins pipeline build config strategy test temporarily
openshift/origin pull request #28718
Opened 2024-04-17 09:04 UTC by apoorvajagtap

Failing Jenkins Pipeline test blocks multiple PRs from merging. As agreed, skipping these tests temporarily.

2024-04-17 09:06 UTC, apoorvajagtap commented
/assign @adambkaplan

2024-04-17 12:06 UTC, adambkaplan approved these changes
/approve

Minor suggestion on the skip message.

2024-04-17 12:06 UTC, adambkaplan commented on test/extended/builds/pipeline_origin_bld.go
> +				g.Skip("the test failure blocks multiple PRs. As this strategy is deprecated, skipping the test to unblock https://issues.redhat.com/browse/OCPBUGS-32293")
```suggestion
				g.Skip("OCPBUGS-32293: temporary skip to unblock build and Jenkins suite tests")
```

2024-04-17 14:09 UTC, sayan-biswas approved these changes

2024-04-18 05:01 UTC, sayan-biswas commented
/lgtm

2024-04-18 13:01 UTC, adambkaplan commented
:thinking: Now I'm wondering why it took us this long to catch the change...

2024-04-18 20:07 UTC, sanchezl commented
/retest

2024-04-19 11:20 UTC, soltysh requested changes
/hold
Where that jenkins-ephemeral is coming from, I checked both https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json and https://github.com/openshift/origin/blob/master/test/extended/testdata/cmd/test/cmd/testdata/jenkins/jenkins-ephemeral-template.json both of these are creating DCs not deployment? 

Alternatively, if you're changing to a deployment (if the above what I said is wrong), you'll need to update logs command in line 65, it currently requests `logs -f dc/jenkins` which if we're working with a deployment should be `logs -f deploy/jenkins`

2024-04-19 12:03 UTC, soltysh commented
Found the culprit in https://github.com/openshift/cluster-samples-operator/pull/540, so yes, aside from that wait, you need to update that run as I mentioned above. 

Also, given we have those two extra places which don't seem to be in-sync with what we have in samples, I'd suggest to sync them as well. To make them all consistent.

2024-04-19 12:04 UTC, soltysh commented
/approve cancel
Please ping me directly on slack once all of the above is fixed, I don't want to have a half baked solution.

2024-04-19 13:18 UTC, soltysh commented
Also `DumpApplicationPodLogs` works for DCs only, so that needs fixing as well.

2024-04-19 14:00 UTC, soltysh commented
Reverting changes to cluster-samples-operator in https://github.com/openshift/cluster-samples-operator/pull/542

2024-04-22 18:51 UTC, adambkaplan commented
/close

Replacing with https://github.com/openshift/origin/pull/28732

2024-04-22 18:52 UTC, closed without merging