OCPBUGS-39373: Update the places missed in PR #29082
openshift/origin pull request #29096
Opened 2024-09-12 09:24 UTC by metlos

Turns out I missed an update of one place important for the image ecosystem perl test.

2024-09-12 09:25 UTC, metlos commented
/test ci/prow/e2e-aws-ovn-image-ecosystem

2024-09-12 09:27 UTC, metlos commented
/test e2e-gcp-ovn-image-ecosystem

2024-09-12 09:32 UTC, metlos commented
/jira refresh

2024-09-12 12:57 UTC, metlos commented
Note that e2e-gcp-ovn-image-ecosystem actually should still fail, but it should not fail because of the perl tests, which is what we are fixing here.

2024-09-12 16:32 UTC, metlos commented
/retest

2024-09-13 06:14 UTC, metlos commented
/retest

2024-09-13 10:20 UTC, metlos commented
/test e2e-gcp-ovn-image-ecosystem

2024-09-13 23:21 UTC, metlos commented
/retest

2024-09-16 15:28 UTC, metlos commented
/test e2e-gcp-ovn-image-ecosystem

2024-09-16 20:31 UTC, metlos commented
/retest

2024-09-18 06:24 UTC, fbm3307 commented
/lgtm

2024-09-18 07:19 UTC, metlos commented
/assign stbenjam

2024-09-18 07:21 UTC, metlos commented
/assign @stbenjam

2024-09-18 15:11 UTC, adambkaplan requested changes
Please squash your commits, and ensure the commit has a well formatted title and description. Include the reasoning for deleting the hotfix portion of the test.

Is there someone from the RHEL team who can verify that this test is a sufficient "smoke test" for the perl s2i image?

2024-09-18 16:57 UTC, metlos commented
@phracek, would you be able to comment on whether the smoke test that we perform is sufficient? Or if not, would you be able to recommend someone that could?

Previously, our test built a custom image from the `perl:5.30-el7` image and a custom app that opens some http endpoint and we checked that it returns the expected data in the http response. Then we also tested that hot-deploy is off by default by trying modifying the filesystem directly in the container and expecting the http response doesn't change.

Afterwards we restarted the image with `PERL_APACHE2_RELOAD=true` and repeated the above procedure, now ensuring that hot deploy is switched on and directly modifying the filesystem of
the container causes Perl to hot-reload the app and return a new http response.

Because `perl:5.30-el7` has been removed, we need to upgrade to the next "oldest" image available that I believe is `perl:5.32-ubi8`.

By looking at https://github.com/sclorg/s2i-perl-container/tree/master/5.32 I found out that the env var to switch hot-deploy on has disappeared from the image and that hot deploy is on
by default.

Therefore I merely removed the part of the test that tests hot-reload switched off.

In your opinion, is testing the perl image using a custom webapp and checking that it a) returns expected data as an http response and b) that hot-deploy works in the image, enough as a smoke test?

2024-09-18 19:16 UTC, metlos commented
/test e2e-gcp-ovn-image-ecosystem

2024-09-18 23:32 UTC, metlos commented
/retest

2024-09-19 09:45 UTC, metlos commented
I'm closing this in favor of https://github.com/openshift/origin/pull/29116.

2024-09-19 09:45 UTC, closed without merging