OCPBUGS-42435: Validate usage of non-standard OCP SCCs via the required-scc monitor test
openshift/origin pull request #29135
Opened 2024-09-26 10:27 UTC by kramaranya

2024-09-26 10:29 UTC, kramaranya commented
/jira refresh

2024-09-26 12:48 UTC, liouk requested changes
What if we have already pinned a non-standard SCC to a namespace that's not allowed?

2024-09-26 12:48 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +				allowedNamespaces := nonStandardSCCNamespaces[validatedSCC]
You can assign `allowedNamespaces` directly at the if statement, where `isNonStandard` is assigned as well.

2024-09-26 12:48 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +	return "cannot suggest required-scc, validated SCC is a custom/non-standard SCC"
Since you can now distinguish between a custom vs non-standard SCC, use separate messages.

2024-10-22 14:25 UTC, kramaranya commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +			if allowedNamespaces, isNonStandard := nonStandardSCCNamespaces[validatedSCC]; isNonStandard && !allowedNamespaces.Has(ns.Name) {
Makes sense! I've updated the code, thanks

2024-10-31 10:33 UTC, kramaranya commented
/retest

2024-10-31 14:09 UTC, kramaranya commented
/retest-required

2024-11-01 10:42 UTC, liouk requested changes

2024-11-01 10:42 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +						"pod '%s' has a non-standard SCC '%s' not allowed in namespace '%s'",
Allowed namespaces would be useful here as well.

2024-11-01 10:42 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +				pod.Name, owners, validatedSCC))
Turn this block into a switch with the custom SCC case as the default, no need to `continue` for every case.

2024-11-13 09:20 UTC, liouk commented
/retest

2024-11-21 09:30 UTC, kramaranya commented
/retest-required

2024-11-21 12:41 UTC, liouk requested changes

2024-11-21 12:41 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +
This should be clear enough:
```suggestion
isFlakingNamespace := ns.Labels["openshift.io/run-level"] == "0" ||
  ns.Labels["openshift.io/run-level"] == "1" ||
  namespacesWithPendingSCCPinning.Has(ns.Name)
```

`len(ns.Labels["openshift.io/run-level"])` could also be enough, but it's better to be explicit.

2024-11-21 12:41 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +		}
In both cases we need one failing `JUnitTestCase`, so append it always. If we need a flake as well, append one.

2024-11-21 12:41 UTC, liouk commented on pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> +		isFlakingNamespace := false
Name suggestion: `flakeWhenFailed`

2024-11-22 08:18 UTC, kramaranya commented
/retest

2024-11-22 12:32 UTC, kramaranya commented
/retest-required

2024-11-22 15:50 UTC, kramaranya commented
/retest-required

2024-11-22 16:20 UTC, kramaranya commented
/label acknowledge-critical-fixes-only

2024-11-23 02:18 UTC, merged

2024-11-24 23:27 UTC, neisw commented
/payload-job periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn-conformance