UDN: Add Network Policy e2e tests
openshift/origin pull request #29195
Opened 2024-10-15 16:27 UTC by pperiyasamy

2024-10-16 11:55 UTC, pperiyasamy commented
/assign @jluhrsen @tssurya @jcaamano

2024-11-06 11:25 UTC, pperiyasamy commented
/test e2e-aws-ovn-single-node-techpreview

2024-11-06 17:11 UTC, pperiyasamy commented
/test e2e-gcp-ovn-techpreview

2024-11-11 11:13 UTC, pperiyasamy commented
/test e2e-gcp-ovn-techpreview

2024-11-11 17:15 UTC, pperiyasamy commented
/test e2e-gcp-ovn-techpreview

2024-11-12 12:24 UTC, pperiyasamy commented
/assign @ricky-rav 

Th tests are ready for review now except NetPol tests are failing due to the bug [OCPBUGS-43519](https://issues.redhat.com/browse/OCPBUGS-43519).

2024-11-12 15:29 UTC, ricky-rav requested changes
Overall looks good, I just added a minor comment. 

I compared the code in `test/extended/networking/network_segmentation_policy.go` to what we have upstream in https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/test/e2e/network_segmentation_policy.go . I see you made a few changes especially for node selection and to adapt the code to what we have in origin to test reachability between two pods. All that looks good to me.

Can you just add a few words to the commit message and mention also the command you used to add the generate code?

Thanks, Peri!

2024-12-04 14:53 UTC, pperiyasamy commented on test/extended/networking/multinetpolicy.go
> +	namespacePodShouldNotReach(oc, "", podName, address)
@ricky-rav passing empty string for namespace is intentional here so that oc exec uses pod from `f.Namespace.Name` namespace.

2024-12-04 14:53 UTC, pperiyasamy commented on test/extended/networking/network_segmentation_policy.go
> +				serverPodConfig.nodeSelector = map[string]string{nodeHostnameKey: workerNodes[len(workerNodes)-1].Name}
yes, right.  guess that should be fine.

2024-12-04 14:54 UTC, pperiyasamy commented
> add a few words to the commit message saying that we're porting to origin the e2e tests we have upstream for network policies and can you also mention also the command you used to add the generate code

yes @ricky-rav, updated the commit message.

2024-12-04 14:56 UTC, pperiyasamy commented
/hold

waiting for https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4789 to be available in d/s for NetPol tests to pass,

2024-12-16 08:48 UTC, pperiyasamy commented
/test e2e-gcp-ovn-techpreview
/test e2e-aws-ovn-single-node-techpreview

2024-12-17 09:13 UTC, ricky-rav commented
/lgtm
Thanks, Peri!

2024-12-17 12:05 UTC, pperiyasamy commented
/test e2e-metal-ipi-ovn-ipv6-techpreview
/test e2e-metal-ipi-ovn-dualstack-techpreview

2024-12-17 12:29 UTC, pperiyasamy commented
/payload-job periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-ipv6-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-dualstack-techpreview

2024-12-17 12:33 UTC, pperiyasamy commented
/assign @dgoodwin @stbenjam

2024-12-17 12:37 UTC, dgoodwin commented
/approve

2024-12-17 13:04 UTC, tssurya commented
/cherry-pick release-4.18

2024-12-18 21:11 UTC, merged