[WIP] primal Ginko tests for 2Node 1Arbiter cluster - testing
openshift/origin pull request #29380
Opened 2024-12-17 13:26 UTC by Neilhamza

2025-02-04 10:25 UTC, suleymanakbas91 requested changes

2025-02-04 10:25 UTC, suleymanakbas91 commented on test/extended/arbiter_topology/OWNERS
> +  - qJkee
We can add @jeff-roche as well. He might also contribute once he is back. Also, please add yourself.

2025-02-10 08:04 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +		infra, err := oc.AdminConfigClient().ConfigV1().Infrastructures().Get(context.Background(), "cluster", metav1.GetOptions{})
moved it to be a global var

2025-02-10 08:04 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +		infra, err := oc.AdminConfigClient().ConfigV1().Infrastructures().Get(context.Background(), "cluster", metav1.GetOptions{})
moved it to be a global var

2025-02-10 08:05 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +		expectedPodCount := 17
currently moved it to top of file - as a future maintenance task it'll be pulled dynamically

2025-02-10 08:05 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +		o.Expect(nodes.Items).To(o.Not(o.BeEmpty()), "Expected to find at least one Arbiter node")
youre correct, update

2025-02-10 08:05 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +		}
updated as requested

2025-02-10 08:06 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +					break endLoop
updated as requested

2025-02-10 08:06 UTC, Neilhamza commented on test/extended/arbiter_topology/OWNERS
> +  - qJkee
added

2025-02-24 16:14 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +	infra, err := oc.AdminConfigClient().ConfigV1().Infrastructures().Get(context.Background(), "cluster", metav1.GetOptions{})
infra cannot be assigned as a global variable for 2 reasons:
each test we see in this file is defined as a suite by it self as it has nothing to do with others tests so beforeach sections only for it's specific test scope
infra as a global variable will fail because the cluster may not be ready yet before starting the tests

2025-02-24 16:18 UTC, Neilhamza commented
/retest

2025-02-25 15:29 UTC, jeff-roche commented on test/extended/arbiter_topology/arbiter_topology.go
> +	infra, err := oc.AdminConfigClient().ConfigV1().Infrastructures().Get(context.Background(), "cluster", metav1.GetOptions{})
Do they need to each be their own suite? The common factor here is an arbiter setup which would warrant grouping them all together under 1 arbiter suite that can then be ignored easily by the rest of OCP if needed

2025-02-27 09:38 UTC, Neilhamza commented on test/extended/arbiter_topology/arbiter_topology.go
> +	infra, err := oc.AdminConfigClient().ConfigV1().Infrastructures().Get(context.Background(), "cluster", metav1.GetOptions{})
since we are testing completely different cluster components

2025-02-28 15:25 UTC, eggfoobar commented
/label tide/merge-method-squash
/lgtm

2025-03-03 19:08 UTC, Neilhamza commented
/retest-required

2025-03-04 03:13 UTC, merged